name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./literary-travels-ui

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Switch to current node version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: './literary-travels-ui/package-lock.json' 

      - name: Install & Test
        run: |
          npm ci
          npm run test

  test-backend:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./literary-travels-api 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Switch to current node version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: './literary-travels-api/package-lock.json'

      - name: Install & Test
        run: |
          npm ci
          npm run test